sudo: false
language: go
go:
  - "1.11.13"
  - "1.12"
  - "1.13"
go_import_path: github.com/twitchscience/kinsumer
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.21.0

script:
  - GO111MODULE=on go test -short ./...
  - GO111MODULE=on golangci-lint run
